addons:
  apt:
    sources:
      - chef-current-xenial
    packages:
      - chef-workstation

install: echo "skip bundle install"

env:
  - CHEF_LICENSE=accept

branches:
  only:
    - master

services: docker

env:
  matrix:
    - INSTANCE=client-ubuntu-1804
    - INSTANCE=client-ubuntu-1910
    - INSTANCE=client-centos-7
    - INSTANCE=client-centos-8
    - INSTANCE=master-ubuntu-1804
    - INSTANCE=master-ubuntu-1910
    - INSTANCE=master-centos-7
    - INSTANCE=master-centos-8
script: KITCHEN_LOCAL_YAML=kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - before_script:
      - chef --version
      - cookstyle --version
      - foodcritic --version
    - script:
      - delivery local all
      env:
        - UNIT_AND_LINT=1
        - CHEF_LICENSE=accept
